version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    depends_on:
      - backend
    ports:
      - 80:80
    volumes: # 挂载本地地址
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./frontend/build/:/var/www/html
      - ./static/:/static/
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000